jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: jaid/action-sync-node-meta@v2.0.0
        with:
          approve: false
          commitMessage: "fix: write GitHub metadata to package.json [{changes}]"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@v1
name: sync-metadata
on:
  schedule:
    - cron: 0 5 * * *
  workflow_dispatch: {}
